#stage-template.yml
parameters:
  environments: #Environments array from pipeline.yml

stages:
  - stage: I_AM_${{ env }}

    jobs:
    - job: A
    - script: echo "Hello from ${{ env }}!"
      displayName: Say Hello
      

    - job: B
    - bash: ls
      displayName: "List Contents"

