#stage-template.yml
parameters:
  environments: #Environments array from pipeline.yml

stages:
  - ${{ each env in parameters.environments }}:
    - stage:  I_AM_${{ env }}
      dependsOn: []
      # by specifying an empty array, this stage doesn't depend on the stage before it
      jobs:
      - job: Echo
        steps:
        - script: echo "Hello from ${{ env }}!"
          displayName: Say Hello
      - job: List
        steps:
        - bash: ls
          displayName: "List Contents"

